### ISSUE TITLE
Dependency issue with `typing_extensions`

### ISSUE THREAD

**Issue by geoffrey-g-delhomme** [anancarv/python-artifactory#119]
**Describe the bug**
Wrong dependency management with `typing_extensions`
```
The conflict is caused by:
    pyartifactory 1.10.1 depends on typing_extensions<4.0.0 and >=3.7.4; python_version >= "3.6" and python_version < "4.0"
    pyartifactory 1.10.1 depends on typing_extensions<5 and >=4; python_version >= "3.7" and python_version < "4.0"
```

**To Reproduce**
With Python 3.10:
```
pip install --upgrade typing_extensions
pip install --upgrade pyartifatory
````

**Expected behavior**
To be compatible with latest versions of typing_extensions.

**Screenshots**
N/A

**Environment:**
 - OS: Linux
 - pyartifactory version: latest
 - Python version: 3.10

**Additional context**
Need to fix `pyproject.toml`:
```
typing_extensions = [
    { version = "^3.7.4", python = "^3.6" },
    { version = "^4", python = "^3.7" },
]
```
Observed while installing other packages depending on the latest typing_extensions module.

**Comment by anancarv** [comment]
Fixed on version v1.10.2 #120
