### ISSUE TITLE
How to support python 2.7

### ISSUE THREAD

**Issue by acaiblog** [anancarv/python-artifactory#132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anancarv** [comment]
Hey @acaiblog,
Unfortunately we're not planning on supporting python 2.7 since it's deprecated for a few years now.

**Comment by themysteq** [comment]
@anancarv Can I co-maintain this project as triage permissions? I would like to be able to answer and eventually close such kind of issues.

@acaiblog there is no way to support Python 2.7 as it's unsupported for few years and from security and people's sane perspective is good to drop python 2.7 completely.
