### ISSUE TITLE
This REST API is available only in Artifactory Pro

### ISSUE THREAD

**Issue by smywhut** [anancarv/python-artifactory#139]
Hi when i run this statement:
from pyartifactory import Artifactory
art = Artifactory(url="ARTIFACTORY_URL", auth=('USERNAME','PASSWORD_OR_API_KEY'), api_version=1)

It shows 400 client error. When I visit http://my-artifactory/api/security/uers according to the URL where the error occurred, the final result shows:

"This REST API is available only in Artifactory Pro (see: jfrog.com/artifactory/features). If you are already running Artifactory Pro please make sure your server is activated with a valid license key.\n"
Is this because my artifactory website doesn't have this feature? But I use dohq-artifactory (which is also a python third-party library), but it is used normally, and can be accessed normally according to the apikey of the artifactory, such as uploading and downloading the artifactory.

**Comment by anancarv** [comment]
Hey @smywhut , this library is a wrapper of this [Artifactory API](https://jfrog.com/help/r/jfrog-rest-apis/introduction-to-the-artifactory-rest-apis).  And as you described earlier, it only works with Artifactory Pro.
