### ISSUE TITLE
How to create Artifactory instance using only access token?

### ISSUE THREAD

**Issue by anancarv** [anancarv/python-artifactory#146]
### Discussed in https://github.com/anancarv/python-artifactory/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **dr4kk4r** April 19, 2023</sup>
From what I can tell currently Artifactory class only allows for authorization via user name and password/api key.

How can I use access token instead?</div>

**Comment by wilmer-suarez-simplisafe** [comment]
I would also like to know if this is possible.

**Comment by anancarv** [comment]
Answered in this discussion: https://github.com/anancarv/python-artifactory/discussions/133
