### ISSUE TITLE
Support new CreateToken API/allow setting custom scope

### ISSUE THREAD

**Issue by NiklasRosenstein** [anancarv/python-artifactory#150]
**Is your feature request related to a problem? Please describe.**

The old Create Token API that is used by `ArtifactorySecurity.create_access_token()` is deprecated: https://jfrog.com/help/r/jfrog-rest-apis/delete-group?tocId=2_OrHvmQlC6dtFFR8F9i3w

![image](https://github.com/anancarv/python-artifactory/assets/1318438/49803778-0e3f-4d7e-a86d-8e36715f1dd2)

**Describe the solution you'd like**

Add support for or use the new Create Token API instead: https://jfrog.com/help/r/jfrog-rest-apis/create-token

![image](https://github.com/anancarv/python-artifactory/assets/1318438/592223dd-ab2c-4a21-8e6b-468a7ca8f0cd)

**Additional context**

We ran into an issue today where all the tokens generated with `pyartifactory` didn't actually have any permissions. It seems the "scope" value of the deprecated API endpoint expects the format of the new endpoint (e.g. "applied-permissions/user" is what we're using now after monkey-patching pyartifactory).

**Comment by anancarv** [comment]
Thanks for pointing it out @NiklasRosenstein . I'll update that feature ASAP

**Comment by NiklasRosenstein** [comment]
Thanks @anancarv !

FYI, this is how I worked around it for now:

```py
def create_access_token(
    self: ArtifactorySecurity,
    user_name: str,
    expires_in: int = 3600,
    refreshable: bool = False,
    groups: list[str] | None = None,
) -> AccessTokenModel:
    """
    A variation of #ArtifactorySecurity.create_access_token() that passes the correct "scope".
    """

    payload = {
        "username": user_name,
        "expires_in": expires_in,
        "refreshable": refreshable,
    }
    payload.update({"scope": "applied-permissions/user"})
    response = self._post(f"api/{self._uri}/token", data=payload, raise_for_status=False)
    if response.ok:
        return AccessTokenModel(**response.json())
    raise InvalidTokenDataException(response.json().get("error_description", "Unknown error"))


ArtifactorySecurity.create_access_token = create_access_token  # type: ignore[method-assign]
```

That being said, JFrog did acknowledge that this as a bug in the old endpoint that was recently introduced:

<img width="1110" alt="image" src="https://github.com/anancarv/python-artifactory/assets/1318438/300d8998-8e69-4942-b073-22383e93e37a">

**Comment by Ashwinmnr** [comment]
Hi @anancarv 

Do we have this feature in any upcoming versions?
We would like to use pyartifactory to authenticate using identity tokens.

Cheers,
Ashwin

**Comment by anancarv** [comment]
> Hi @anancarv
> 
> Do we have this feature in any upcoming versions? We would like to use pyartifactory to authenticate using identity tokens.
> 
> Cheers, Ashwin

Hey @Ashwinmnr, I've created a PR #192 to support the new create-token API.
