### ISSUE TITLE
Builds API missing

### ISSUE THREAD

**Issue by gpongelli** [anancarv/python-artifactory#166]
**Is your feature request related to a problem? Please describe.**
I saw this package miss [Builds API](https://jfrog.com/help/r/jfrog-rest-apis/builds), is it planned to be added in future ?

**Describe alternatives you've considered**
Find and use a different package that manages builds. 

Thanks,

**Comment by anancarv** [comment]
> **Is your feature request related to a problem? Please describe.** I saw this package miss [Builds API](https://jfrog.com/help/r/jfrog-rest-apis/builds), is it planned to be added in future ?
> 
> **Describe alternatives you've considered** Find and use a different package that manages builds.
> 
> Thanks,

Hey @gpongelli, the addition of this feature is not planned. But contributions are welcome, you can create a new MR and I'll review it
