### ISSUE TITLE
Create repo transmits "*****" as password (from SecretStr __str__())

### ISSUE THREAD

**Issue by BrukerJWD** [anancarv/python-artifactory#179]
**Describe the bug**
When creating a repository with a password, this password is transmitted as stars only in the REST request:
`"password": "**********"`
Of course, this is not the real password which should be sent instead :)

Updating the password of a repository works though, so I had a look at the difference.

I think you are missing a `model_dump()` in [create_repo()](https://github.com/anancarv/python-artifactory/blob/275735b6e40222436f56e36c149ca5976fd608ed/pyartifactory/objects/repository.py#L105):

    data = json.dumps(repo.model_dump(), default=custom_encoder)

Currently, the SecretStr is not transformed correctly to a string in the `data` dict.

**To Reproduce**
1. Define remote repository with password and call `artifactory.repositories.create_repo(defined_repo)`
2. Look at the REST request. Or try the Connection Test in Artifactory for this repo: It fails.

**Expected behavior**
The password has to be transmitted

**Environment:**
 - OS: Linux
 - pyartifactory version: 2.1.3
 - Python version: 3.9

**Comment by anancarv** [comment]
Good catch. Thanks for pointing it out. I've created a MR to fix that
