### ISSUE TITLE
Upload with Checksum does not work --> creates empty file in artifactory

### ISSUE THREAD

**Issue by Lect0r905** [anancarv/python-artifactory#182]
**Describe the bug**
when using deploy with checksum the uploaded file is 0 byte:
- The checksum calculation is wrong, the file needs to be opened for every hashing function (switch line 27 & 28 in artifact.py) 
- the put command for checksum_enabled is missing the data
- if a directory is selected the deploy command is not deploying with checksum_enabled

**To Reproduce**
use artifact.deploy with checksum_enabled

**Expected behavior**
file is uploaded with checksum

**Environment:**
 - OS: Windows
 - pyartifactory version: 2.5.0

**Comment by anancarv** [comment]
Hey @Lect0r905 ,
Thanks for raising. You're right for the first and the third comments. 

However, for the second one:
> the put command for checksum_enabled is missing the data

According to the [Artifactory API](https://jfrog.com/help/r/jfrog-rest-apis/deploy-artifact-by-checksum), the deploy by checksum deploys an artifact to the specified destination by checking if the artifact content already exists in Artifactory. So no need for the data to be sent.  But I'll add the possibility to send the data as well

**Comment by anancarv** [comment]
> Hey @Lect0r905 , Thanks for raising. You're right for the first and the third comments.
> 
> However, for the second one:
> 
> > the put command for checksum_enabled is missing the data
> 
> According to the [Artifactory API](https://jfrog.com/help/r/jfrog-rest-apis/deploy-artifact-by-checksum), the deploy by checksum deploys an artifact to the specified destination by checking if the artifact content already exists in Artifactory. So no need for the data to be sent. But I'll add the possibility to send the data as well

Actually, you're right. The stream should also be sent. Fixing that

**Comment by anancarv** [comment]
> Hey @Lect0r905 , Thanks for raising. You're right for the first and the third comments.
> 
> However, for the second one:
> 
> > the put command for checksum_enabled is missing the data
> 
> According to the [Artifactory API](https://jfrog.com/help/r/jfrog-rest-apis/deploy-artifact-by-checksum), the deploy by checksum deploys an artifact to the specified destination by checking if the artifact content already exists in Artifactory. So no need for the data to be sent. But I'll add the possibility to send the data as well

I just re-checked the documentation, and I confirm that there is no need to send the data stream when deploying by checksum

**Comment by foutoucour** [comment]
I confirm the bug, that I introduced :(

Here is a PR to fix the situation: https://github.com/anancarv/python-artifactory/pull/186
