### ISSUE TITLE
Remote Artifactory Version

### ISSUE THREAD

**Issue by ManiAm** [anancarv/python-artifactory#196]
How can I get the remote antifactory version upon connect.
Is there any APIs to do that?

**Comment by anancarv** [comment]
> How can I get the remote antifactory version upon connect. Is there any APIs to do that?

Hey @ManiAm, by default the API version is 1 (See [README](https://github.com/anancarv/python-artifactory?tab=readme-ov-file#basic-authentication)). You can set the desired api_version when creating the Artifactory object using the param `api_version`. However, as written in the README it will only be used for the permissions management. Feel free to propose a new MR for allowing it to other resources
