### ISSUE TITLE
Add a TODO list of next changes to implement

### ISSUE THREAD

**Issue by gueyeb** [anancarv/python-artifactory#21]
A simple TODO list for next changes :

- Build artifacts

- etc ...

**Comment by nymous** [comment]
I'd say we should create issues for this, maybe with a specific tag if they are too big and need to be broken down (something like `roadmap` for long-term issues, and maybe an "epic" tag to group the big issue and the smaller ones).

**Comment by gueyeb** [comment]
Yes indeed. That'd work fine too :)

**Comment by anancarv** [comment]
Hi @gueyeb,

If you want to be aware of what we're working on and have a view on next changes, there is now a kanban board with opened issues & PRs.
https://github.com/anancarv/python-artifactory/projects/1

:wink:

**Comment by gueyeb** [comment]
Awesome guys. That's pretty neat. I'll be checking it out from time to time.
Keep up the good work.
Cheers ! 🎊
