### ISSUE TITLE
Implementation of Access token feature 

### ISSUE THREAD

**Issue by Arlington1985** [anancarv/python-artifactory#23]
Thanks for your work. It's one of the best artifactory library. It would be great if it also would contain access token DML features

**Comment by anancarv** [comment]
Hi @Arlington1985 ,
There is a new pull request for implementing access token feature: #29 

We'll let you know when it's released

**Comment by Arlington1985** [comment]
Great, looking forward to it

**Comment by anancarv** [comment]
Hi @Arlington1985 ,
**pyartifactory** v1.1.0 has been released. You can find there the access token feature developped by @dogfish182 you asked for. Don't hesitate to give feedbacks and contribute if you like the project :smiley:

**Comment by Arlington1985** [comment]
Thanks guys for the hard work. I will give a shoot and will let you know.

**Comment by Arlington1985** [comment]
Do you know that you can actually publish it here?
https://github.com/jfrog

**Comment by anancarv** [comment]
Can we ? Okay, I'll contact the members of the organization to propose them the project :). Thanks for the tip
