### ISSUE TITLE
art.artifacts.properties(artifact_path): artifact_path doesn't support querystring 'properties'  

### ISSUE THREAD

**Issue by sachinik19** [anancarv/python-artifactory#50]
**Describe the bug**
The current implementation of method properies(self, artifact_path) defined in 'pyartifactory/objects.py' uses the rest endpoint url format string - **"api/storage/{artifact_path}?properties[=x[,y]]"**

Here **"?properties[=x[,y]]"** is a bug as the user cannot set it's value using arguments. 

Due to that, it's not possible to provide the arguments for 'properties' querystring param. Ideally the format string should simply be **"api/storage/{artifact_path}"**, thus user can pass the artifact_path for eg: "my-repository/my/new/artifact/directory/file.txt?properties=buildname,jobid" etc. 

By default artifactory rest api just sends general properties. To get other properties, you need to pass the name of properties in querystring.

**To Reproduce**
1. Try to pass the artifact_path i provided in example. 
2. See error

**Expected behavior**
It should allow the user of the method to pass the value of properties querystring param. 

**Screenshots**

**Environment:**
 - OS: [e.g. Linux / Windows / macOS]
 - pyartifactory version [e.g. 1.4.0], get it with:
```
python -c "import pyartifactory; print(pyartifactory.__version__)"
```
 - Python version, get it with:
```
python --version
```

**Additional context**

**Comment by anancarv** [comment]
Hi @sachinik19 ,
Thanks for the very clear bug description, it's very clear and will be very easy to reproduce :+1: . We'll fix it ASAP and let you know as soon as the patch is released.

**Comment by sachinik19** [comment]
Thanks @anancarv for the quick response, it means a lot as our product needs it urgently.

**Comment by sachinik19** [comment]
Hi @anancarv, curious to know when can we see the fix for it. Let me know if I can be of any help to expedite it.

**Comment by nymous** [comment]
Hello!
Yes a PR is on the way, sorry for the delay
