### ISSUE TITLE
Deploying artifacts adds extraneous MIME content

### ISSUE THREAD

**Issue by mx00s** [anancarv/python-artifactory#60]
**Describe the bug**
When deploying an artifact the local file's bytes get embedded in a multipart MIME message.

**To Reproduce**
1. Create a small test file.
2. Deploy it as described in the README.
3. Download the deployed file, again as described in the README.
4. Diff the downloaded file with the original and notice the downloaded file has additional MIME context.
5. Re-download using the UI and notice that it too has extraneous bytes.

**Expected behavior**
Downloading the artifact using any client, including the UI, should produce a file which is binary equivalent to the file uploaded with this client.

**Environment:**
 - OS: Linux
 - pyartifactory version: 1.7.1
 - Python version: 3.8.5

**Comment by anancarv** [comment]
Hi @mx00s 
Thanks for pointing this issue out. It will be patched ASAP

**Comment by nymous** [comment]
The 1.7.2 released just now should fix your issue!

**Comment by mx00s** [comment]
Thanks for the quick fix! I verified 1.7.2 works as expected.
