### ISSUE TITLE
Add a command-line tool similar to jfrog

### ISSUE THREAD

**Issue by stefanseefeld** [anancarv/python-artifactory#68]
Would there be an interest to add a command-line "frontend" to this project that acts somewhat like the `jfrog` tool, but uses all the functionality implemented by this `pyartifactory` Python package ?

I'd be happy to start this, covering the "artifact" domain, i.e. moving data around. Someone else could then expand this to other domains such as repo and user management.

**Comment by anancarv** [comment]
Hi @stefanseefeld ,
I don't think it's the goal of this project. Indeed, here we focus more on the library itself. But if you want to create a CLI based on `pyartifactory` you can do it on a separate project. I'm sure some people will be interested.

**Comment by stefanseefeld** [comment]
OK, fair enough. Thanks !
