### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by Simkod** [anancarv/python-artifactory#70]
**Describe the bug**
Can`t communicate with artifactory

**Expected behavior**
The script downloads the file to the given location

**Screenshots**
![image](https://user-images.githubusercontent.com/45272799/95432272-bd1fa980-094e-11eb-9799-80f6265f25e9.png)

**Environment:**
 - OS: Windows 10
 - pyartifactory version 1.8.0
-python 3.7.3

**Environment:**
Also, using the artifactory URL and the credentials(username, password) in a browser, the download works without problem.
At the company the same script runs without problem on other machines, so the problem is most likely machine specific.

**Comment by anancarv** [comment]
Hi,
Can you please remove your except statement and re-run your script ? This way, we can have the full trace of the error message

**Comment by Simkod** [comment]
Hello,
This is the result without exception. The file exists in the artifactory, and if I write the URL of it in the browser, I can download it.
![2](https://user-images.githubusercontent.com/45272799/95449424-0d096b00-0965-11eb-81dd-5551c632cee4.JPG)

**Comment by Simkod** [comment]
Crashes here:
![image](https://user-images.githubusercontent.com/45272799/95450292-5c03d000-0966-11eb-8387-75e05de577e4.png)

**Comment by Simkod** [comment]
I installed pyartifactory version 1.6, it is working now.

**Comment by anancarv** [comment]
There is no major changes about the artifact info retrieval between version 1.6 and 1.8. I do not get why this error is happening to you. Are you sure your artifact_path has the following structure: `libs-release-local/ch/qos/logback/logback-classic/0.9.9/logback-classic-0.9.9.jar` ?

**Comment by Simkod** [comment]
Yes, it had that structure. 
It also works with 1.7, it helps maybe to narrow it down. 
Thank you for your support!

**Comment by anancarv** [comment]
You're welcome, thanks for your feedback. I'm going to check what it happens in 1.8.0

**Comment by anancarv** [comment]
Hi @Simkod ,
Can you retry to download files using the new version of pyartifactory `1.8.1` please ? You shoul not encounter issues any more
