### ISSUE TITLE
Publish artifact checksum values on deploy

### ISSUE THREAD

**Issue by saper** [anancarv/python-artifactory#80]
**Is your feature request related to a problem? Please describe.**
Artifacts deployed with the `deploy` method end up with the following warning in the Artifactory web interface:

> Client did not publish a checksum value.
> If you trust the uploaded artifact you can accept the actual checksum by clicking the 'Fix Checksum' button.

**Describe the solution you'd like**

I want all three checksums (SHA-256, SHA-1, MD5) to be provided and checked.

**Describe alternatives you've considered**
Don't use python-artifactory, just upload directory with HTTP

I am willing to develop that feature, the question I have is the project active and accepts pull requests?

**Comment by anancarv** [comment]
Hi @saper ,
Yes the project is active and accepts pull requests. You can make a PR and we'll have a look a it

**Comment by thenewnano** [comment]
@saper  I started a draft, I haven't even run it yet, so in no way ready yet, take a look https://github.com/thenewnano/python-artifactory/commit/3c095f88f5e4153d1feffbf3769d038eb16b4016

**Comment by daveyc** [comment]
@thenewnano do you plan to open a PR for your patch?

**Comment by foutoucour** [comment]
Hello everyone,
I proposed a PR for this issue: https://github.com/anancarv/python-artifactory/pull/175

The update will help the usage of the library in [Autodesk](https://www.autodesk.com/).

**Comment by anancarv** [comment]
Hello everyone,
The feature has been released on https://github.com/anancarv/python-artifactory/releases/tag/v2.5.0 🚀 .

Thanks @foutoucour for your PR.
