### ISSUE TITLE
Best practice for using files

### ISSUE THREAD

**Issue by chamoisla** [anancarv/python-artifactory#82]
General question. Say I have a CSV file with a list of artifacts to delete. What do you suggest for passing CSV data into `art.artifacts.delete("<ARTIFACT_PATH_IN_ARTIFACTORY>")` instead of hard coding a single repository path?

**Comment by anancarv** [comment]
Hi @chamoisla ,
For your use case, you can complete your CSV file with the artifact paths instead of just the artifacts. Then, you can loop through your CSV and run `art.artifacts.delete("<ARTIFACT_PATH_IN_ARTIFACTORY>")`
