### ISSUE TITLE
Add support for setting artifact properties

### ISSUE THREAD

**Issue by thenewnano** [anancarv/python-artifactory#91]
**Is your feature request related to a problem? Please describe.**
When uploading a build I need to set a key=value properties for that artifact/build. currently only get is implemented for properties. 

**Describe the solution you'd like**
provide two new methods in artifact class to implement:
Set Item Properties
Update Item Properties

**Describe alternatives you've considered**
Wrapping jfrog CLI for now

**Additional context**
https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-SetItemProperties

**Comment by anancarv** [comment]
Thanks for this issue, we'll work on it as soon as possible
