### ISSUE TITLE
Add a method to find out whether an artifact exists

### ISSUE THREAD

**Issue by janhollevoet** [anancarv/python-artifactory#93]
Add a method that checks whether an artifact exists:

`artifact_info = art.artifacts.exists("<ARTIFACT_PATH_IN_ARTIFACTORY>")`

Currently, this can be done with the info method, combined with try/except.

**Comment by anancarv** [comment]
Hi @janhollevoet ,
This project is a wrapper for the Artifactory API. So we try to follow the [API specification](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API). The endpoint for checking that an artifact exist or not is not defined within it, so we prefer not to add it. However, as you showed it earlier, it's still possible to perform such a check. I suggest you to in your code something like that:

```
try
      artifact_info = art.artifacts.info("<ARTIFACT_PATH_IN_ARTIFACTORY>")
      ....
except ArtifactNotFoundException:
     ...
     log.error("Artifact does not exist")
```

**Comment by bdsoha** [comment]
@janhollevoet Is this issue still relevant, or can it be closed?
