### ISSUE TITLE
Support "File List"?

### ISSUE THREAD

**Issue by deeplook** [anancarv/python-artifactory#94]
The REST API mentions a feature named "File List" as described on https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-FileList. Is there any plan to implement this?

**Comment by anancarv** [comment]
Hi @deeplook ,
There is no plan yet to adding this feature. However, if urgent, you can create a PR and I'll be glad to review and merge it.
